name: Deploy Contoso_University_Core

on:
  workflow_run:
    workflows: ["Pack Contoso_University_Core"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclussion== 'success' }}
    environment: production
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: https://org09903175.crm.dynamics.com
          user-name: ${{ secrets.USERNAME }}
          password-secrets: ${{ secrets.PASSWORD }}
          solution-file: contoso_university_core_managed.zip